### ISSUE TITLE
Check for SKETCHUP_CONSOLE.show

### ISSUE THREAD

**Issue by thomthom** [SketchUp/rubocop-sketchup#135]
`SKETCHUP_CONSOLE.show` is for development, not something an extension should typically do, unless it's a development tool. 

However, developers might add this temporarily for debugging and forget to remove it before publishing.

Warn against usage of `SKETCHUP_CONSOLE.show` - if it's a false positive for the rare cases of a development tool it can be disabled for the project.

**Comment by Eneroth3** [comment]
Duplicate of #84
