### ISSUE TITLE
Warn about usage of `sleep`

### ISSUE THREAD

**Issue by thomthom** [SketchUp/rubocop-sketchup#144]
Often the usage of `sleep` is a code smell. Consider a cop to flag this usage to guide EW reviewers for closer inspection of it's usage.

**Comment by Eneroth3** [comment]
Are there examples of when `sleep` can be used? I'm thinking of how to phrase the message in the cop.

Reasons not to use it is how it freezes up SketchUp and `UI.start_timer` can maybe be used as an alternative.

**Comment by thomthom** [comment]
I've seen it usually as a way to deal with async behaviour. The appropriate solution would be to wait for an event that signal the completion of whatever you're waiting for. (Like HTTP requests)

Othertimes it can be animations.
