### ISSUE TITLE
Run in SU?

### ISSUE THREAD

**Issue by MSP-Greg** [SketchUp/rubocop-sketchup#50]
ReadMe states:
'This is not intended to be used inside of SketchUp'

Do you think it would be helpful if it could?  Just wondering...

**Comment by thomthom** [comment]
I don't see how you would even use it inside SketchUp. Nor do I quite see the benefit...

This is static analysis of your source code - the tool is a CLI app that you run from the console or wired up to your editor.

If you have an idea of how it could be useful from within a running instance of SU then I'm all hears.

**Comment by MSP-Greg** [comment]
Whether it runs inside SU or from a command prompt should generate the same output.  If you don't think it would be helpful, that's fine.

You know better than I how many EW dev's do or don't have a standalone Ruby install...

**Comment by thomthom** [comment]
We are planning to offer this gem as a webservice that can be run by uploading an RBZ. That should take care of developers who doesn't want to install standalone Ruby.

This gem will also be part of future Extension Warehouse moderation automation.

**Comment by MSP-Greg** [comment]
Cool.  From my perspective, I'd rather encourage EW dev's to use/experiment with stand-alone Ruby anyway.  Encourages things like checking with 'frozen strings', etc...
