### ISSUE TITLE
Validate the pattern of `Sketchup::Licensing.get_extension_license`

### ISSUE THREAD

**Issue by thomthom** [SketchUp/rubocop-sketchup#65]
There have been cases where the ID string passed to `Sketchup::Licensing.get_extension_license` hasn't been valid. Extra spaces etc. Add a cop that match the pattern of the GUID string.

**Comment by Eneroth3** [comment]
+1 for this.

The way the value is printed on the Extension Warehouse website makes it extremely easy to grab an extra space. Triple click and the space is included, at least in Firefox. The website could perhaps also be updated to not print white spaces around the identifier.

![2018-08-13_13h39_23](https://user-images.githubusercontent.com/5631725/44029654-5caa6b06-9efe-11e8-8d74-25a0266b3bf2.gif)

**Comment by thomthom** [comment]
Also, check if the license ID is coming from anything other than a string literal or local variable. Otherwise the GUID string can be tampered with by reflection.
