### ISSUE TITLE
Check for UI.Toolbar.restore timer hack

### ISSUE THREAD

**Issue by thomthom** [SketchUp/rubocop-sketchup#71]
https://github.com/SketchUp/api-issue-tracker/issues/125

```ruby
# No longer needed:
UI.start_timer(0.1, false){ tb.restore }#Use timer as workaround for bug 2902434.
```

Also recommend using `UI::Toolbar#restore` over manually checking last state.

---

Versions where `toolbar.restore` work fine:

- [x] SketchUp 2018
- [x] SketchUp 2017
- [x] SketchUp 2016
- [x] SketchUp 2015
- [x] SketchUp 2014
- [x] SketchUp 2013
- [x] SketchUp 8
- [x] SketchUp 7
- [x] SketchUp 6

---

http://ruby.sketchup.com/file.ReleaseNotes.html#label-What-27s+new+in+SketchUp+2013+M1

> What's new in SketchUp 2013 M1
> Bug Fixes
> Fixed a toolbar bug that caused some extensions to not display and become incorrectly docked behind other toolbars. Developers are now advised to call Toolbar.restore after creating a toolbar, although those that do not will also work correctly on SU2013 M1.

---

https://sketchucation.com/forums/viewtopic.php?f=180&t=24763#p298170

```ruby
state = tb.get_last_state
if (state == TB_VISIBLE)
  tb.restore
  # Per bug 2902434, adding a timer call to restore the toolbar. This
  # fixes a toolbar resizing regression on PC as the restore() call
  # does not seem to work as the script is first loading.
  UI.start_timer(0.1, false) {
  tb.restore
}
end
```

---

The internal logic of `.restore` is currently (SU2018):

```cpp
void CSketchUpToolbar::Restore() {
  if (GetSavedState() != TB_HIDDEN )
    Show();
}
```

Not sure if this changed since SU6 - which might account for the manual state check in the old examples.

**Comment by thomthom** [comment]
`toolbar.restore` appear to work all the way back to SU6.

I don't see the need to use `UI.start_timer`. Nor do I see any need to use `toolbar.show` - as that would override user preferences.

**Comment by DanRathbun** [comment]
> _toolbar.restore appear to work all the way back to SU6._

This is strange because you yourself said in a public post that you saw the bug on Windows but only with large toolbar icons set.
I don't think we have a way in the API to "sniff" out the icon size setting the user is using (unless we perhaps read the registry or JSON files.)

_REF:_ [http://sketchucation.com/forums/viewtopic.php?f=180&t=32474](http://sketchucation.com/forums/viewtopic.php?f=180&t=32474)
This is in the time frame (just post release of) SketchUp 8 M0.

Also link to API Issue question: [125 : Preferred way to show toolbar?](https://github.com/SketchUp/api-issue-tracker/issues/125)

**Comment by DanRathbun** [comment]
... and in a forum topic 5 years ago, you indicated you thought the bug was pre-2014, but were not sure ...
https://forums.sketchup.com/t/workarounds-for-backward-compatibilty/6678

**Comment by thomthom** [comment]
hm.. 

There might still be issues with `.restore` in terms of properly restoring/showing the toolbar.

But the need for the timer hack should be long time gone.

**Comment by DanRathbun** [comment]
I'd hope so. Ie, It's (or was) an internal bug that should be logged and fixed. 
(I also think it only presented itself when the toolbar was floating.)

**Comment by thomthom** [comment]
I think it was related to the old toolbar controls SU used.

**Comment by Eneroth3** [comment]
I don't think people on the outside know much about new vs old toolbar controls (I haven't heard of it before).

Do you know approximately around what version this changed?

**Comment by DanRathbun** [comment]
I think the new toolbar controls were introduced with SU2013. That is when their tooltips became the nifty 2 liners.
